# Generated by Django 4.2.5 on 2024-02-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referal_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
