# Generated by Django 4.2.5 on 2024-02-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referal_code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
