# Generated by Django 4.2.5 on 2024-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
