# Generated by Django 4.2.5 on 2024-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_referal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
