# Generated by Django 4.2.5 on 2023-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, default='xyz.png', upload_to='Product-Images')),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ['-id'],
            },
        ),
    ]
