# Generated by Django 4.2.5 on 2024-02-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_profile_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sapre', 'Sapre'), ('Parity', 'Parity'), ('Bcone', 'Bcone')], max_length=20)),
                ('final_number', models.CharField(blank=True, max_length=20)),
                ('final_color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_prediction', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Voilet-Green', 'Voilet-Green'), ('Voilet-Red', 'Voilet-Red')], max_length=20)),
                ('number_prediction', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('0', 'Ten')], max_length=100)),
                ('bet_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_correct_prediction', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
