# Generated by Django 4.2.5 on 2023-11-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='baingan'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_color', models.CharField(choices=[('P', 'Parity'), ('S', 'Sapre'), ('B', 'Bcone')], max_length=1)),
                ('player_prediction', models.CharField(choices=[('P', 'Parity'), ('S', 'Sapre'), ('B', 'Bcone')], default=('S', 'Sapre'), max_length=1)),
                ('correct_prediction', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
