# Generated by Django 4.2.5 on 2024-02-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_game_options_alter_player_color_prediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at', '-name']},
        ),
    ]
